# Generated by Django 3.1.2 on 2020-11-09 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BestProductSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_selection', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=14, unique=True)),
                ('brand', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=400)),
                ('last_modified', models.DateTimeField()),
                ('ingredients', models.TextField()),
                ('energy_kcal', models.IntegerField()),
                ('nutrition_score', models.CharField(max_length=1)),
                ('sugars_100g', models.IntegerField()),
                ('fat_100g', models.IntegerField()),
                ('selection', models.ManyToManyField(through='food_items.BestProductSelection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
                ('products', models.ManyToManyField(to='food_items.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=560)),
                ('products', models.ManyToManyField(to='food_items.Product')),
            ],
        ),
        migrations.AddField(
            model_name='bestproductselection',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_items.product'),
        ),
        migrations.AddField(
            model_name='bestproductselection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
