# Generated by Django 3.1.2 on 2020-12-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0003_auto_20201127_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='https://static.openfoodfacts.org/images/misc/openfoodfacts-logo-en-178x150.png'),
        ),
    ]
