# Generated by Django 3.1.2 on 2020-12-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0005_auto_20201213_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='https://static.openfoodfacts.org/images/misc/openfoodfacts-logo-en-178x150.png', null=True),
        ),
    ]
